// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Cvt_RGB_to_YCrCb (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state9 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_reg_589;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] ap_reg_pp0_iter4_exitcond_reg_589;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] j_reg_174;
wire   [0:0] exitcond5_fu_185_p2;
wire    ap_CS_fsm_state2;
wire   [10:0] i_3_fu_191_p2;
reg   [10:0] i_3_reg_584;
wire   [0:0] exitcond_fu_197_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_reg_589;
reg   [0:0] ap_reg_pp0_iter2_exitcond_reg_589;
reg   [0:0] ap_reg_pp0_iter3_exitcond_reg_589;
wire   [10:0] j_2_fu_203_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_94_reg_598;
reg   [7:0] ap_reg_pp0_iter2_tmp_94_reg_598;
reg   [7:0] tmp_95_reg_607;
reg   [7:0] ap_reg_pp0_iter2_tmp_95_reg_607;
reg   [7:0] tmp_96_reg_614;
reg   [7:0] ap_reg_pp0_iter2_tmp_96_reg_614;
wire   [13:0] grp_fu_556_p3;
reg   [13:0] tmp2_reg_622;
reg    ap_enable_reg_pp0_iter2;
wire   [40:0] grp_fu_564_p3;
reg   [40:0] p_Val2_7_reg_627;
wire   [15:0] tmp_20_fu_262_p2;
reg   [15:0] tmp_20_reg_632;
reg   [7:0] y_V_reg_637;
reg   [7:0] u_V_reg_642;
wire   [16:0] tmp4_fu_424_p2;
reg   [16:0] tmp4_reg_647;
reg   [3:0] tmp_88_reg_652;
reg   [3:0] tmp_89_reg_657;
wire   [7:0] p_y_V_fu_474_p3;
reg   [7:0] p_y_V_reg_662;
wire   [7:0] p_u_V_fu_486_p3;
reg   [7:0] p_u_V_reg_668;
wire   [7:0] p_v_V_fu_509_p3;
reg   [7:0] p_v_V_reg_674;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [10:0] i_reg_163;
reg    ap_block_state1;
wire    ap_CS_fsm_state9;
reg    ap_block_pp0_stage0_01001;
wire   [12:0] tmp35_fu_215_p3;
wire   [14:0] p_shl4_fu_226_p3;
wire   [11:0] p_shl5_fu_237_p3;
wire   [15:0] p_shl4_cast_fu_233_p1;
wire   [15:0] p_shl5_cast_fu_244_p1;
wire   [15:0] p_Val2_6_fu_248_p2;
wire  signed [39:0] p_Val2_14_cast_fu_254_p1;
wire   [7:0] tmp_20_fu_262_p1;
wire   [15:0] OP2_V_1_cast1_fu_209_p1;
wire   [13:0] p_shl1_fu_271_p3;
wire   [8:0] p_shl2_fu_282_p3;
wire   [14:0] p_shl1_cast_fu_278_p1;
wire   [14:0] p_shl2_cast_fu_289_p1;
wire   [14:0] p_shl3_fu_299_p3;
wire   [14:0] p_Val2_s_fu_293_p2;
wire   [15:0] p_shl3_cast_fu_306_p1;
wire   [15:0] tmp_cast_fu_310_p1;
wire   [15:0] tmp2_cast_fu_320_p1;
wire   [15:0] tmp1_fu_314_p2;
wire   [15:0] tmp_s_fu_323_p2;
wire   [11:0] p_shl8_fu_339_p3;
wire   [8:0] p_shl9_fu_354_p3;
wire   [12:0] p_shl8_cast1_fu_346_p1;
wire   [12:0] p_shl9_cast_fu_361_p1;
wire   [12:0] p_Val2_3_fu_365_p2;
wire   [41:0] tmp_27_fu_371_p1;
wire   [41:0] tmp_28_fu_374_p1;
wire   [41:0] p_Val2_20_fu_378_p2;
wire   [41:0] addconv_fu_384_p2;
wire   [14:0] p_shl_fu_400_p3;
wire   [15:0] p_shl_cast_fu_407_p1;
wire   [15:0] p_shl8_cast_fu_350_p1;
wire  signed [15:0] grp_fu_572_p3;
wire   [15:0] p_Val2_5_fu_411_p2;
wire   [16:0] tmp_56_cast_fu_417_p1;
wire   [16:0] tmp_57_cast_fu_420_p1;
wire   [17:0] tmp4_cast_fu_450_p1;
wire   [17:0] tmp_29_fu_453_p2;
wire   [0:0] icmp_fu_469_p2;
wire   [0:0] icmp5_fu_481_p2;
wire   [3:0] tmp_90_fu_493_p4;
wire   [0:0] icmp8_fu_503_p2;
wire   [7:0] v_V_fu_459_p4;
wire   [0:0] tmp_31_fu_517_p2;
wire   [0:0] tmp_33_fu_530_p2;
wire   [0:0] tmp_35_fu_543_p2;
wire   [5:0] grp_fu_556_p0;
wire   [7:0] grp_fu_556_p1;
wire   [12:0] grp_fu_556_p2;
wire   [7:0] grp_fu_564_p0;
wire   [7:0] grp_fu_564_p1;
wire   [39:0] grp_fu_564_p2;
wire  signed [6:0] grp_fu_572_p0;
wire   [7:0] grp_fu_572_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [13:0] grp_fu_556_p10;
wire   [13:0] grp_fu_556_p20;
wire   [40:0] grp_fu_564_p20;
wire   [14:0] grp_fu_572_p10;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

contrastadj_mac_mbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 14 ))
contrastadj_mac_mbkb_U13(
    .din0(grp_fu_556_p0),
    .din1(grp_fu_556_p1),
    .din2(grp_fu_556_p2),
    .dout(grp_fu_556_p3)
);

contrastadj_mac_mcud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 40 ),
    .dout_WIDTH( 41 ))
contrastadj_mac_mcud_U14(
    .din0(grp_fu_564_p0),
    .din1(grp_fu_564_p1),
    .din2(grp_fu_564_p2),
    .dout(grp_fu_564_p3)
);

contrastadj_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
contrastadj_mac_mdEe_U15(
    .din0(grp_fu_572_p0),
    .din1(grp_fu_572_p1),
    .din2(tmp_20_reg_632),
    .dout(grp_fu_572_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond5_fu_185_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond5_fu_185_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((exitcond5_fu_185_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_reg_163 <= i_3_reg_584;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_163 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_reg_174 <= j_2_fu_203_p2;
    end else if (((exitcond5_fu_185_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_174 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_reg_pp0_iter1_exitcond_reg_589 <= exitcond_reg_589;
        exitcond_reg_589 <= exitcond_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_reg_pp0_iter2_exitcond_reg_589 <= ap_reg_pp0_iter1_exitcond_reg_589;
        ap_reg_pp0_iter2_tmp_94_reg_598 <= tmp_94_reg_598;
        ap_reg_pp0_iter2_tmp_95_reg_607 <= tmp_95_reg_607;
        ap_reg_pp0_iter2_tmp_96_reg_614 <= tmp_96_reg_614;
        ap_reg_pp0_iter3_exitcond_reg_589 <= ap_reg_pp0_iter2_exitcond_reg_589;
        ap_reg_pp0_iter4_exitcond_reg_589 <= ap_reg_pp0_iter3_exitcond_reg_589;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_3_reg_584 <= i_3_fu_191_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter1_exitcond_reg_589 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_7_reg_627 <= grp_fu_564_p3;
        tmp2_reg_622 <= grp_fu_556_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter3_exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_u_V_reg_668 <= p_u_V_fu_486_p3;
        p_v_V_reg_674 <= p_v_V_fu_509_p3;
        p_y_V_reg_662 <= p_y_V_fu_474_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter2_exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp4_reg_647 <= tmp4_fu_424_p2;
        tmp_88_reg_652 <= {{tmp_s_fu_323_p2[15:12]}};
        tmp_89_reg_657 <= {{addconv_fu_384_p2[15:12]}};
        u_V_reg_642 <= {{addconv_fu_384_p2[15:8]}};
        y_V_reg_637 <= {{tmp_s_fu_323_p2[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter1_exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_20_reg_632 <= tmp_20_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_589 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_94_reg_598 <= p_src_data_stream_0_V_dout;
        tmp_95_reg_607 <= p_src_data_stream_1_V_dout;
        tmp_96_reg_614 <= p_src_data_stream_2_V_dout;
    end
end

always @ (*) begin
    if ((exitcond_fu_197_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond5_fu_185_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond5_fu_185_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_reg_589 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_reg_589 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_reg_589 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_reg_589 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond5_fu_185_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_fu_197_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((exitcond_fu_197_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP2_V_1_cast1_fu_209_p1 = tmp_95_reg_607;

assign addconv_fu_384_p2 = (42'd32768 + p_Val2_20_fu_378_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_reg_589 == 1'd0) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_reg_589 == 1'd0) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_reg_589 == 1'd0) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_0_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((exitcond_reg_589 == 1'd0) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_reg_589 == 1'd0) & (p_src_data_stream_0_V_empty_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter5 = (((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((ap_reg_pp0_iter4_exitcond_reg_589 == 1'd0) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond5_fu_185_p2 = ((i_reg_163 == 11'd1080) ? 1'b1 : 1'b0);

assign exitcond_fu_197_p2 = ((j_reg_174 == 11'd1920) ? 1'b1 : 1'b0);

assign grp_fu_556_p0 = 14'd25;

assign grp_fu_556_p1 = grp_fu_556_p10;

assign grp_fu_556_p10 = tmp_96_reg_614;

assign grp_fu_556_p2 = grp_fu_556_p20;

assign grp_fu_556_p20 = tmp35_fu_215_p3;

assign grp_fu_564_p0 = 16'd94;

assign grp_fu_564_p1 = OP2_V_1_cast1_fu_209_p1;

assign grp_fu_564_p2 = grp_fu_564_p20;

assign grp_fu_564_p20 = $unsigned(p_Val2_14_cast_fu_254_p1);

assign grp_fu_572_p0 = 15'd32730;

assign grp_fu_572_p1 = grp_fu_572_p10;

assign grp_fu_572_p10 = ap_reg_pp0_iter2_tmp_94_reg_598;

assign i_3_fu_191_p2 = (i_reg_163 + 11'd1);

assign icmp5_fu_481_p2 = ((tmp_89_reg_657 == 4'd0) ? 1'b1 : 1'b0);

assign icmp8_fu_503_p2 = ((tmp_90_fu_493_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_fu_469_p2 = ((tmp_88_reg_652 == 4'd0) ? 1'b1 : 1'b0);

assign j_2_fu_203_p2 = (j_reg_174 + 11'd1);

assign p_Val2_14_cast_fu_254_p1 = $signed(p_Val2_6_fu_248_p2);

assign p_Val2_20_fu_378_p2 = (tmp_27_fu_371_p1 - tmp_28_fu_374_p1);

assign p_Val2_3_fu_365_p2 = (p_shl8_cast1_fu_346_p1 + p_shl9_cast_fu_361_p1);

assign p_Val2_5_fu_411_p2 = (p_shl_cast_fu_407_p1 - p_shl8_cast_fu_350_p1);

assign p_Val2_6_fu_248_p2 = (p_shl4_cast_fu_233_p1 - p_shl5_cast_fu_244_p1);

assign p_Val2_s_fu_293_p2 = (p_shl1_cast_fu_278_p1 + p_shl2_cast_fu_289_p1);

assign p_dst_data_stream_0_V_din = ((tmp_31_fu_517_p2[0:0] === 1'b1) ? 8'd235 : p_y_V_reg_662);

assign p_dst_data_stream_1_V_din = ((tmp_33_fu_530_p2[0:0] === 1'b1) ? 8'd239 : p_u_V_reg_668);

assign p_dst_data_stream_2_V_din = ((tmp_35_fu_543_p2[0:0] === 1'b1) ? 8'd239 : p_v_V_reg_674);

assign p_shl1_cast_fu_278_p1 = p_shl1_fu_271_p3;

assign p_shl1_fu_271_p3 = {{ap_reg_pp0_iter2_tmp_94_reg_598}, {6'd0}};

assign p_shl2_cast_fu_289_p1 = p_shl2_fu_282_p3;

assign p_shl2_fu_282_p3 = {{ap_reg_pp0_iter2_tmp_94_reg_598}, {1'd0}};

assign p_shl3_cast_fu_306_p1 = p_shl3_fu_299_p3;

assign p_shl3_fu_299_p3 = {{ap_reg_pp0_iter2_tmp_95_reg_607}, {7'd0}};

assign p_shl4_cast_fu_233_p1 = p_shl4_fu_226_p3;

assign p_shl4_fu_226_p3 = {{tmp_94_reg_598}, {7'd0}};

assign p_shl5_cast_fu_244_p1 = p_shl5_fu_237_p3;

assign p_shl5_fu_237_p3 = {{tmp_94_reg_598}, {4'd0}};

assign p_shl8_cast1_fu_346_p1 = p_shl8_fu_339_p3;

assign p_shl8_cast_fu_350_p1 = p_shl8_fu_339_p3;

assign p_shl8_fu_339_p3 = {{ap_reg_pp0_iter2_tmp_96_reg_614}, {4'd0}};

assign p_shl9_cast_fu_361_p1 = p_shl9_fu_354_p3;

assign p_shl9_fu_354_p3 = {{ap_reg_pp0_iter2_tmp_96_reg_614}, {1'd0}};

assign p_shl_cast_fu_407_p1 = p_shl_fu_400_p3;

assign p_shl_fu_400_p3 = {{ap_reg_pp0_iter2_tmp_96_reg_614}, {7'd0}};

assign p_u_V_fu_486_p3 = ((icmp5_fu_481_p2[0:0] === 1'b1) ? 8'd16 : u_V_reg_642);

assign p_v_V_fu_509_p3 = ((icmp8_fu_503_p2[0:0] === 1'b1) ? 8'd16 : v_V_fu_459_p4);

assign p_y_V_fu_474_p3 = ((icmp_fu_469_p2[0:0] === 1'b1) ? 8'd16 : y_V_reg_637);

assign tmp1_fu_314_p2 = (p_shl3_cast_fu_306_p1 + tmp_cast_fu_310_p1);

assign tmp2_cast_fu_320_p1 = tmp2_reg_622;

assign tmp35_fu_215_p3 = {{5'd16}, {tmp_95_reg_607}};

assign tmp4_cast_fu_450_p1 = tmp4_reg_647;

assign tmp4_fu_424_p2 = (tmp_56_cast_fu_417_p1 + tmp_57_cast_fu_420_p1);

assign tmp_20_fu_262_p1 = OP2_V_1_cast1_fu_209_p1;

assign tmp_20_fu_262_p2 = ($signed(16'd65462) * $signed({{1'b0}, {tmp_20_fu_262_p1}}));

assign tmp_27_fu_371_p1 = p_Val2_7_reg_627;

assign tmp_28_fu_374_p1 = p_Val2_3_fu_365_p2;

assign tmp_29_fu_453_p2 = (18'd32768 + tmp4_cast_fu_450_p1);

assign tmp_31_fu_517_p2 = ((p_y_V_reg_662 > 8'd235) ? 1'b1 : 1'b0);

assign tmp_33_fu_530_p2 = ((p_u_V_reg_668 > 8'd239) ? 1'b1 : 1'b0);

assign tmp_35_fu_543_p2 = ((p_v_V_reg_674 > 8'd239) ? 1'b1 : 1'b0);

assign tmp_56_cast_fu_417_p1 = $unsigned(grp_fu_572_p3);

assign tmp_57_cast_fu_420_p1 = p_Val2_5_fu_411_p2;

assign tmp_90_fu_493_p4 = {{tmp_29_fu_453_p2[15:12]}};

assign tmp_cast_fu_310_p1 = p_Val2_s_fu_293_p2;

assign tmp_s_fu_323_p2 = (tmp2_cast_fu_320_p1 + tmp1_fu_314_p2);

assign v_V_fu_459_p4 = {{tmp_29_fu_453_p2[15:8]}};

endmodule //Cvt_RGB_to_YCrCb
