// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmy_rgb2gray.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMy_rgb2gray_CfgInitialize(XMy_rgb2gray *InstancePtr, XMy_rgb2gray_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMy_rgb2gray_Start(XMy_rgb2gray *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMy_rgb2gray_IsDone(XMy_rgb2gray *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMy_rgb2gray_IsIdle(XMy_rgb2gray *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMy_rgb2gray_IsReady(XMy_rgb2gray *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMy_rgb2gray_EnableAutoRestart(XMy_rgb2gray *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMy_rgb2gray_DisableAutoRestart(XMy_rgb2gray *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_AP_CTRL, 0);
}

void XMy_rgb2gray_InterruptGlobalEnable(XMy_rgb2gray *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_GIE, 1);
}

void XMy_rgb2gray_InterruptGlobalDisable(XMy_rgb2gray *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_GIE, 0);
}

void XMy_rgb2gray_InterruptEnable(XMy_rgb2gray *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_IER);
    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_IER, Register | Mask);
}

void XMy_rgb2gray_InterruptDisable(XMy_rgb2gray *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_IER);
    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMy_rgb2gray_InterruptClear(XMy_rgb2gray *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMy_rgb2gray_WriteReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_ISR, Mask);
}

u32 XMy_rgb2gray_InterruptGetEnabled(XMy_rgb2gray *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_IER);
}

u32 XMy_rgb2gray_InterruptGetStatus(XMy_rgb2gray *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMy_rgb2gray_ReadReg(InstancePtr->Axilites_BaseAddress, XMY_RGB2GRAY_AXILITES_ADDR_ISR);
}

