-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter2D is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of Filter2D is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_43A : STD_LOGIC_VECTOR (10 downto 0) := "10000111010";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_438 : STD_LOGIC_VECTOR (10 downto 0) := "10000111000";
    constant ap_const_lv11_437 : STD_LOGIC_VECTOR (10 downto 0) := "10000110111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv11_782 : STD_LOGIC_VECTOR (10 downto 0) := "11110000010";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_780 : STD_LOGIC_VECTOR (11 downto 0) := "011110000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_EFE : STD_LOGIC_VECTOR (11 downto 0) := "111011111110";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond388_i_reg_973 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_exitcond388_i_reg_973 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_i_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_or_cond_i_i_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_944 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal or_cond_i_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter4_or_cond_i_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_3_reg_235 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond389_i_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_V_fu_252_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_V_reg_930 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_s_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_105_not_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_105_not_reg_939 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_949 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_149_1_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_149_1_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_957 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_304_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_34_reg_963 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_8_2_t_fu_308_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_8_2_t_reg_968 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond388_i_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op104_read_state5 : BOOLEAN;
    signal ap_predicate_op115_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_reg_pp0_iter2_exitcond388_i_reg_973 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_324_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ImagLoc_x_fu_346_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_reg_982 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_cond_i_i_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_p2_i_i_fu_392_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_p2_i_i_reg_992 : STD_LOGIC_VECTOR (11 downto 0);
    signal sel_tmp8_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_reg_998 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1003 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_brmerge_reg_1003 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_or_cond_i_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_or_cond_i_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_or_cond_i_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_455_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_40_reg_1014 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_3_addr_reg_1019 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_addr_reg_1025 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_addr_reg_1031 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_buf_0_val_0_0_fu_501_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_reg_1037 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_fu_539_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_reg_1042 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_582_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_reg_1047 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_593_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_reg_1052 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_20_reg_1057 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_16_1_2_fu_668_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_16_1_2_reg_1062 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_46_fu_712_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_46_reg_1067 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp19_fu_716_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp19_reg_1072 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp20_fu_722_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp20_reg_1077 : STD_LOGIC_VECTOR (7 downto 0);
    signal isneg_reg_1082 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_fu_810_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_4_reg_1088 : STD_LOGIC_VECTOR (7 downto 0);
    signal not_i_i_i_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_i_i_i_reg_1093 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter2_state5 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal k_buf_0_val_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce0 : STD_LOGIC;
    signal k_buf_0_val_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_3_ce1 : STD_LOGIC;
    signal k_buf_0_val_3_we1 : STD_LOGIC;
    signal k_buf_0_val_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce0 : STD_LOGIC;
    signal k_buf_0_val_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_4_ce1 : STD_LOGIC;
    signal k_buf_0_val_4_we1 : STD_LOGIC;
    signal k_buf_0_val_4_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce0 : STD_LOGIC;
    signal k_buf_0_val_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_ce1 : STD_LOGIC;
    signal k_buf_0_val_5_we1 : STD_LOGIC;
    signal k_buf_0_val_5_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_V_reg_224 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_21_fu_459_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal src_kernel_win_0_va_fu_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_18_fu_604_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_15_fu_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_16_fu_120 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_19_fu_609_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_17_fu_124 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_s_fu_128 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_14_fu_132 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_15_fu_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_16_fu_140 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_fu_520_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_17_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_18_fu_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_33_fu_270_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_35_fu_330_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal t_V_4_cast_fu_314_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_37_fu_352_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_378_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_1_fu_386_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_21_not_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp2_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_2_fu_434_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_assign_5_fu_439_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_fu_445_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal col_assign_cast8_fu_451_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_assign_1_fu_484_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_489_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_508_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_527_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_7_0_1_fu_630_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_193_0_2_cast_cas_fu_642_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_193_0_cast_cast_fu_626_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp16_fu_652_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_193_0_cast_fu_638_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp16_cast_fu_658_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal OP1_V_2_cast_fu_674_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_7_2_fu_678_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_27_fu_646_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_43_fu_662_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_2_2_cast_fu_698_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_7_2_2_fu_702_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_193_2_cast_cast_fu_684_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_193_2_2_cast_cas_fu_708_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_28_fu_692_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_44_fu_688_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl_fu_757_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_cast_fu_764_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_7_2_1_fu_768_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_16_1_2_cast_fu_754_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_193_2_1_cast_fu_774_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp18_fu_782_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp19_cast_fu_788_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_3_fu_791_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_45_fu_778_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp21_fu_805_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_fu_815_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_i_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i_85_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mux_i_i_cast_fu_841_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_338 : BOOLEAN;
    signal ap_condition_332 : BOOLEAN;

    component img_filter_mux_32hbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Filter2D88_k_buf_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_3_U : component Filter2D88_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_3_address0,
        ce0 => k_buf_0_val_3_ce0,
        q0 => k_buf_0_val_3_q0,
        address1 => k_buf_0_val_3_addr_reg_1019,
        ce1 => k_buf_0_val_3_ce1,
        we1 => k_buf_0_val_3_we1,
        d1 => p_src_data_stream_V_dout);

    k_buf_0_val_4_U : component Filter2D88_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_4_address0,
        ce0 => k_buf_0_val_4_ce0,
        q0 => k_buf_0_val_4_q0,
        address1 => k_buf_0_val_4_addr_reg_1025,
        ce1 => k_buf_0_val_4_ce1,
        we1 => k_buf_0_val_4_we1,
        d1 => k_buf_0_val_4_d1);

    k_buf_0_val_5_U : component Filter2D88_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_5_address0,
        ce0 => k_buf_0_val_5_ce0,
        q0 => k_buf_0_val_5_q0,
        address1 => k_buf_0_val_5_addr_reg_1031,
        ce1 => k_buf_0_val_5_ce1,
        we1 => k_buf_0_val_5_we1,
        d1 => k_buf_0_val_5_d1);

    img_filter_mux_32hbi_U44 : component img_filter_mux_32hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_s_fu_128,
        din1 => right_border_buf_0_14_fu_132,
        din2 => ap_const_lv8_0,
        din3 => col_assign_1_fu_484_p2,
        dout => tmp_22_fu_489_p5);

    img_filter_mux_32hbi_U45 : component img_filter_mux_32hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_16_fu_140,
        din1 => right_border_buf_0_17_fu_144,
        din2 => ap_const_lv8_0,
        din3 => col_assign_1_fu_484_p2,
        dout => tmp_23_fu_508_p5);

    img_filter_mux_32hbi_U46 : component img_filter_mux_32hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_18_fu_148,
        din1 => right_border_buf_0_15_fu_136,
        din2 => ap_const_lv8_0,
        din3 => col_assign_1_fu_484_p2,
        dout => tmp_24_fu_527_p5);

    img_filter_mux_32hbi_U47 : component img_filter_mux_32hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_501_p3,
        din1 => col_buf_0_val_1_0_fu_520_p3,
        din2 => col_buf_0_val_2_0_fu_539_p3,
        din3 => tmp_34_reg_963,
        dout => tmp_25_fu_582_p5);

    img_filter_mux_32hbi_U48 : component img_filter_mux_32hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_501_p3,
        din1 => col_buf_0_val_1_0_fu_520_p3,
        din2 => col_buf_0_val_2_0_fu_539_p3,
        din3 => row_assign_8_2_t_reg_968,
        dout => tmp_26_fu_593_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((exitcond389_i_fu_246_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((exitcond388_i_fu_318_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((exitcond389_i_fu_246_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter2_state5)) then 
                        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((exitcond389_i_fu_246_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_V_3_reg_235_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond388_i_fu_318_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                t_V_3_reg_235 <= j_V_fu_324_p2;
            elsif (((exitcond389_i_fu_246_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_3_reg_235 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    t_V_reg_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                t_V_reg_224 <= i_V_reg_930;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_224 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond388_i_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ImagLoc_x_reg_982 <= ImagLoc_x_fu_346_p2;
                brmerge_reg_1003 <= brmerge_fu_424_p2;
                or_cond_i_i_reg_987 <= or_cond_i_i_fu_372_p2;
                or_cond_i_reg_1010 <= or_cond_i_fu_429_p2;
                p_p2_i_i_reg_992 <= p_p2_i_i_fu_392_p3;
                sel_tmp8_reg_998 <= sel_tmp8_fu_418_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_reg_pp0_iter1_brmerge_reg_1003 <= brmerge_reg_1003;
                ap_reg_pp0_iter1_exitcond388_i_reg_973 <= exitcond388_i_reg_973;
                ap_reg_pp0_iter1_or_cond_i_i_reg_987 <= or_cond_i_i_reg_987;
                ap_reg_pp0_iter1_or_cond_i_reg_1010 <= or_cond_i_reg_1010;
                exitcond388_i_reg_973 <= exitcond388_i_fu_318_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_reg_pp0_iter2_exitcond388_i_reg_973 <= ap_reg_pp0_iter1_exitcond388_i_reg_973;
                ap_reg_pp0_iter2_or_cond_i_reg_1010 <= ap_reg_pp0_iter1_or_cond_i_reg_1010;
                ap_reg_pp0_iter3_or_cond_i_reg_1010 <= ap_reg_pp0_iter2_or_cond_i_reg_1010;
                ap_reg_pp0_iter4_or_cond_i_reg_1010 <= ap_reg_pp0_iter3_or_cond_i_reg_1010;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                col_buf_0_val_0_0_reg_1037 <= col_buf_0_val_0_0_fu_501_p3;
                col_buf_0_val_2_0_reg_1042 <= col_buf_0_val_2_0_fu_539_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_V_reg_930 <= i_V_fu_252_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond389_i_fu_246_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_reg_944 <= icmp_fu_280_p2;
                row_assign_8_2_t_reg_968 <= row_assign_8_2_t_fu_308_p2;
                tmp_105_not_reg_939 <= tmp_105_not_fu_264_p2;
                tmp_149_1_reg_953 <= tmp_149_1_fu_292_p2;
                tmp_16_reg_949 <= tmp_16_fu_286_p2;
                tmp_17_reg_957 <= tmp_17_fu_298_p2;
                tmp_34_reg_963 <= tmp_34_fu_304_p1;
                tmp_s_reg_935 <= tmp_s_fu_258_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_reg_pp0_iter3_or_cond_i_reg_1010 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                isneg_reg_1082 <= p_Val2_3_fu_791_p2(10 downto 10);
                not_i_i_i_reg_1093 <= not_i_i_i_fu_825_p2;
                p_Val2_4_reg_1088 <= p_Val2_4_fu_810_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                k_buf_0_val_3_addr_reg_1019 <= tmp_21_fu_459_p1(11 - 1 downto 0);
                k_buf_0_val_4_addr_reg_1025 <= tmp_21_fu_459_p1(11 - 1 downto 0);
                k_buf_0_val_5_addr_reg_1031 <= tmp_21_fu_459_p1(11 - 1 downto 0);
                tmp_40_reg_1014 <= tmp_40_fu_455_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_reg_pp0_iter2_or_cond_i_reg_1010 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_Val2_16_1_2_reg_1062 <= p_Val2_16_1_2_fu_668_p2;
                src_kernel_win_0_va_20_reg_1057 <= src_kernel_win_0_va_fu_112;
                tmp19_reg_1072 <= tmp19_fu_716_p2;
                tmp20_reg_1077 <= tmp20_fu_722_p2;
                tmp_46_reg_1067 <= tmp_46_fu_712_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                right_border_buf_0_14_fu_132 <= right_border_buf_0_s_fu_128;
                right_border_buf_0_15_fu_136 <= right_border_buf_0_18_fu_148;
                right_border_buf_0_16_fu_140 <= col_buf_0_val_1_0_fu_520_p3;
                right_border_buf_0_17_fu_144 <= right_border_buf_0_16_fu_140;
                right_border_buf_0_18_fu_148 <= col_buf_0_val_2_0_fu_539_p3;
                right_border_buf_0_s_fu_128 <= col_buf_0_val_0_0_fu_501_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_reg_pp0_iter2_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_15_fu_116 <= src_kernel_win_0_va_fu_112;
                src_kernel_win_0_va_16_fu_120 <= src_kernel_win_0_va_19_fu_609_p3;
                src_kernel_win_0_va_17_fu_124 <= src_kernel_win_0_va_16_fu_120;
                src_kernel_win_0_va_fu_112 <= src_kernel_win_0_va_18_fu_604_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_17_reg_957 = ap_const_lv1_1) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_25_reg_1047 <= tmp_25_fu_582_p5;
                tmp_26_reg_1052 <= tmp_26_fu_593_p5;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, exitcond389_i_fu_246_p2, ap_CS_fsm_state2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond389_i_fu_246_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ImagLoc_x_fu_346_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(t_V_4_cast_fu_314_p1));
    OP1_V_2_2_cast_fu_698_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_18_fu_604_p3),9));
    OP1_V_2_cast_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_15_fu_116),9));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state9 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_or_cond_i_reg_1010, ap_predicate_op104_read_state5, ap_predicate_op115_read_state5)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_reg_pp0_iter4_or_cond_i_reg_1010 = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op104_read_state5 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_or_cond_i_reg_1010, ap_predicate_op104_read_state5, ap_predicate_op115_read_state5)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_reg_pp0_iter4_or_cond_i_reg_1010 = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op104_read_state5 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_or_cond_i_reg_1010, ap_predicate_op104_read_state5, ap_predicate_op115_read_state5)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_reg_pp0_iter4_or_cond_i_reg_1010 = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op104_read_state5 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter2_assign_proc : process(p_src_data_stream_V_empty_n, ap_predicate_op104_read_state5, ap_predicate_op115_read_state5)
    begin
                ap_block_state5_pp0_stage0_iter2 <= (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op104_read_state5 = ap_const_boolean_1)));
    end process;

        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter5_assign_proc : process(p_dst_data_stream_V_full_n, ap_reg_pp0_iter4_or_cond_i_reg_1010)
    begin
                ap_block_state8_pp0_stage0_iter5 <= ((ap_reg_pp0_iter4_or_cond_i_reg_1010 = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0));
    end process;


    ap_condition_332_assign_proc : process(ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_16_reg_949)
    begin
                ap_condition_332 <= ((tmp_16_reg_949 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0));
    end process;


    ap_condition_338_assign_proc : process(ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_149_1_reg_953)
    begin
                ap_condition_338 <= ((tmp_149_1_reg_953 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0));
    end process;


    ap_condition_pp0_exit_iter2_state5_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter2_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter2_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, exitcond389_i_fu_246_p2, ap_CS_fsm_state2)
    begin
        if (((exitcond389_i_fu_246_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op104_read_state5_assign_proc : process(ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944)
    begin
                ap_predicate_op104_read_state5 <= ((ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0));
    end process;


    ap_predicate_op115_read_state5_assign_proc : process(ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_s_reg_935)
    begin
                ap_predicate_op115_read_state5 <= ((tmp_s_reg_935 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(exitcond389_i_fu_246_p2, ap_CS_fsm_state2)
    begin
        if (((exitcond389_i_fu_246_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_424_p2 <= (tmp_19_fu_366_p2 or tmp_105_not_reg_939);
    col_assign_1_fu_484_p2 <= (tmp_40_reg_1014 xor ap_const_lv2_3);
        col_assign_cast8_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_fu_445_p3),32));

    col_buf_0_val_0_0_fu_501_p3 <= 
        k_buf_0_val_3_q0 when (ap_reg_pp0_iter1_brmerge_reg_1003(0) = '1') else 
        tmp_22_fu_489_p5;
    col_buf_0_val_1_0_fu_520_p3 <= 
        k_buf_0_val_4_q0 when (ap_reg_pp0_iter1_brmerge_reg_1003(0) = '1') else 
        tmp_23_fu_508_p5;
    col_buf_0_val_2_0_fu_539_p3 <= 
        k_buf_0_val_5_q0 when (ap_reg_pp0_iter1_brmerge_reg_1003(0) = '1') else 
        tmp_24_fu_527_p5;
    exitcond388_i_fu_318_p2 <= "1" when (t_V_3_reg_235 = ap_const_lv11_782) else "0";
    exitcond389_i_fu_246_p2 <= "1" when (t_V_reg_224 = ap_const_lv11_43A) else "0";
    i_V_fu_252_p2 <= std_logic_vector(unsigned(t_V_reg_224) + unsigned(ap_const_lv11_1));
    icmp2_fu_340_p2 <= "0" when (tmp_35_fu_330_p4 = ap_const_lv10_0) else "1";
    icmp_fu_280_p2 <= "0" when (tmp_33_fu_270_p4 = ap_const_lv10_0) else "1";
    j_V_fu_324_p2 <= std_logic_vector(unsigned(t_V_3_reg_235) + unsigned(ap_const_lv11_1));
    k_buf_0_val_3_address0 <= tmp_21_fu_459_p1(11 - 1 downto 0);

    k_buf_0_val_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_16_reg_949, ap_predicate_op115_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_16_reg_949 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_3_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_16_reg_949, ap_predicate_op115_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_16_reg_949 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_3_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_4_address0 <= tmp_21_fu_459_p1(11 - 1 downto 0);

    k_buf_0_val_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_149_1_reg_953, ap_predicate_op115_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_149_1_reg_953 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_4_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_d1_assign_proc : process(p_src_data_stream_V_dout, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, ap_predicate_op115_read_state5, k_buf_0_val_3_q0, ap_condition_338)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((ap_predicate_op115_read_state5 = ap_const_boolean_1)) then 
                k_buf_0_val_4_d1 <= k_buf_0_val_3_q0;
            elsif ((ap_const_boolean_1 = ap_condition_338)) then 
                k_buf_0_val_4_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_4_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_4_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_4_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_149_1_reg_953, ap_predicate_op115_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_149_1_reg_953 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_4_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_5_address0 <= tmp_21_fu_459_p1(11 - 1 downto 0);

    k_buf_0_val_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_16_reg_949, ap_predicate_op115_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_16_reg_949 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_d1_assign_proc : process(p_src_data_stream_V_dout, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, ap_predicate_op115_read_state5, k_buf_0_val_4_q0, ap_condition_332)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if ((ap_predicate_op115_read_state5 = ap_const_boolean_1)) then 
                k_buf_0_val_5_d1 <= k_buf_0_val_4_q0;
            elsif ((ap_const_boolean_1 = ap_condition_332)) then 
                k_buf_0_val_5_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_5_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_5_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_5_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_16_reg_949, ap_predicate_op115_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_16_reg_949 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    not_i_i_i_fu_825_p2 <= "0" when (tmp_29_fu_815_p4 = ap_const_lv3_0) else "1";
    or_cond_i_fu_429_p2 <= (icmp_reg_944 and icmp2_fu_340_p2);
    or_cond_i_i_fu_372_p2 <= (tmp_19_fu_366_p2 and rev_fu_360_p2);
    overflow_fu_836_p2 <= (tmp_i_i_fu_831_p2 and not_i_i_i_reg_1093);
    p_Val2_16_1_2_cast_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_16_1_2_reg_1062),11));
    p_Val2_16_1_2_fu_668_p2 <= std_logic_vector(unsigned(tmp_193_0_cast_fu_638_p1) + unsigned(tmp16_cast_fu_658_p1));
    p_Val2_3_fu_791_p2 <= std_logic_vector(unsigned(tmp18_fu_782_p2) + unsigned(tmp19_cast_fu_788_p1));
    p_Val2_4_fu_810_p2 <= std_logic_vector(unsigned(tmp20_reg_1077) + unsigned(tmp21_fu_805_p2));
    p_assign_1_fu_386_p2 <= std_logic_vector(unsigned(ap_const_lv12_1) - unsigned(t_V_4_cast_fu_314_p1));
    p_assign_2_fu_434_p2 <= std_logic_vector(signed(ap_const_lv12_EFE) - signed(p_p2_i_i_reg_992));
    p_assign_5_fu_439_p3 <= 
        ImagLoc_x_reg_982 when (or_cond_i_i_reg_987(0) = '1') else 
        p_assign_2_fu_434_p2;

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_or_cond_i_reg_1010)
    begin
        if (((ap_reg_pp0_iter4_or_cond_i_reg_1010 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= 
        p_mux_i_i_cast_fu_841_p3 when (tmp_i_i_85_fu_849_p2(0) = '1') else 
        p_Val2_4_reg_1088;

    p_dst_data_stream_V_write_assign_proc : process(ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_or_cond_i_reg_1010, ap_block_pp0_stage0_11001)
    begin
        if (((ap_reg_pp0_iter4_or_cond_i_reg_1010 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_mux_i_i_cast_fu_841_p3 <= 
        ap_const_lv8_FF when (tmp_i_i_fu_831_p2(0) = '1') else 
        ap_const_lv8_0;
    p_p2_i_i_fu_392_p3 <= 
        p_assign_1_fu_386_p2 when (tmp_38_fu_378_p3(0) = '1') else 
        ImagLoc_x_fu_346_p2;
    p_shl_cast_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_757_p3),10));
    p_shl_fu_757_p3 <= (src_kernel_win_0_va_20_reg_1057 & ap_const_lv1_0);

    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, ap_reg_pp0_iter1_exitcond388_i_reg_973, ap_reg_pp0_iter1_or_cond_i_i_reg_987, icmp_reg_944, tmp_s_reg_935)
    begin
        if ((((tmp_s_reg_935 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_1) and (ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_reg_pp0_iter1_or_cond_i_i_reg_987 = ap_const_lv1_1) and (icmp_reg_944 = ap_const_lv1_0) and (ap_reg_pp0_iter1_exitcond388_i_reg_973 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op104_read_state5, ap_predicate_op115_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op115_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op104_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    r_V_7_0_1_fu_630_p3 <= (src_kernel_win_0_va_16_fu_120 & ap_const_lv1_0);
    r_V_7_2_1_fu_768_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(p_shl_cast_fu_764_p1));
    r_V_7_2_2_fu_702_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(OP1_V_2_2_cast_fu_698_p1));
    r_V_7_2_fu_678_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(OP1_V_2_cast_fu_674_p1));
    rev_fu_360_p2 <= (tmp_37_fu_352_p3 xor ap_const_lv1_1);
    row_assign_8_2_t_fu_308_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(tmp_34_fu_304_p1));
    sel_tmp7_fu_412_p2 <= (tmp_37_fu_352_p3 or tmp_21_not_fu_406_p2);
    sel_tmp8_fu_418_p2 <= (tmp_20_fu_400_p2 and sel_tmp7_fu_412_p2);
    src_kernel_win_0_va_18_fu_604_p3 <= 
        tmp_25_reg_1047 when (tmp_17_reg_957(0) = '1') else 
        col_buf_0_val_0_0_reg_1037;
    src_kernel_win_0_va_19_fu_609_p3 <= 
        tmp_26_reg_1052 when (tmp_17_reg_957(0) = '1') else 
        col_buf_0_val_2_0_reg_1042;
    t_V_4_cast_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_3_reg_235),12));
    tmp16_cast_fu_658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp16_fu_652_p2),10));
    tmp16_fu_652_p2 <= std_logic_vector(unsigned(tmp_193_0_2_cast_cas_fu_642_p1) + unsigned(tmp_193_0_cast_cast_fu_626_p1));
    tmp18_fu_782_p2 <= std_logic_vector(unsigned(p_Val2_16_1_2_cast_fu_754_p1) + unsigned(tmp_193_2_1_cast_fu_774_p1));
        tmp19_cast_fu_788_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp19_reg_1072),11));

    tmp19_fu_716_p2 <= std_logic_vector(signed(tmp_193_2_cast_cast_fu_684_p1) + signed(tmp_193_2_2_cast_cas_fu_708_p1));
    tmp20_fu_722_p2 <= std_logic_vector(unsigned(tmp_28_fu_692_p2) + unsigned(tmp_44_fu_688_p1));
    tmp21_fu_805_p2 <= std_logic_vector(unsigned(tmp_46_reg_1067) + unsigned(tmp_45_fu_778_p1));
    tmp_105_not_fu_264_p2 <= "1" when (unsigned(t_V_reg_224) > unsigned(ap_const_lv11_437)) else "0";
    tmp_149_1_fu_292_p2 <= "1" when (t_V_reg_224 = ap_const_lv11_0) else "0";
    tmp_16_fu_286_p2 <= "1" when (t_V_reg_224 = ap_const_lv11_1) else "0";
    tmp_17_fu_298_p2 <= "1" when (unsigned(t_V_reg_224) > unsigned(ap_const_lv11_438)) else "0";
    tmp_193_0_2_cast_cas_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_19_fu_609_p3),9));
    tmp_193_0_cast_cast_fu_626_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_17_fu_124),9));
    tmp_193_0_cast_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_7_0_1_fu_630_p3),10));
        tmp_193_2_1_cast_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_7_2_1_fu_768_p2),11));

        tmp_193_2_2_cast_cas_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_7_2_2_fu_702_p2),10));

        tmp_193_2_cast_cast_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_7_2_fu_678_p2),10));

    tmp_19_fu_366_p2 <= "1" when (signed(ImagLoc_x_fu_346_p2) < signed(ap_const_lv12_780)) else "0";
    tmp_20_fu_400_p2 <= "1" when (signed(p_p2_i_i_fu_392_p3) < signed(ap_const_lv12_780)) else "0";
    tmp_21_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_assign_cast8_fu_451_p1),64));
    tmp_21_not_fu_406_p2 <= (tmp_19_fu_366_p2 xor ap_const_lv1_1);
    tmp_27_fu_646_p2 <= std_logic_vector(unsigned(src_kernel_win_0_va_17_fu_124) + unsigned(src_kernel_win_0_va_19_fu_609_p3));
    tmp_28_fu_692_p2 <= std_logic_vector(unsigned(tmp_27_fu_646_p2) + unsigned(tmp_43_fu_662_p2));
    tmp_29_fu_815_p4 <= p_Val2_3_fu_791_p2(10 downto 8);
    tmp_33_fu_270_p4 <= t_V_reg_224(10 downto 1);
    tmp_34_fu_304_p1 <= t_V_reg_224(2 - 1 downto 0);
    tmp_35_fu_330_p4 <= t_V_3_reg_235(10 downto 1);
    tmp_37_fu_352_p3 <= ImagLoc_x_fu_346_p2(11 downto 11);
    tmp_38_fu_378_p3 <= ImagLoc_x_fu_346_p2(11 downto 11);
    tmp_40_fu_455_p1 <= x_fu_445_p3(2 - 1 downto 0);
    tmp_43_fu_662_p2 <= std_logic_vector(shift_left(unsigned(src_kernel_win_0_va_16_fu_120),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_44_fu_688_p1 <= r_V_7_2_fu_678_p2(8 - 1 downto 0);
    tmp_45_fu_778_p1 <= r_V_7_2_1_fu_768_p2(8 - 1 downto 0);
    tmp_46_fu_712_p1 <= r_V_7_2_2_fu_702_p2(8 - 1 downto 0);
    tmp_i_i_85_fu_849_p2 <= (overflow_fu_836_p2 or isneg_reg_1082);
    tmp_i_i_fu_831_p2 <= (isneg_reg_1082 xor ap_const_lv1_1);
    tmp_s_fu_258_p2 <= "1" when (unsigned(t_V_reg_224) < unsigned(ap_const_lv11_438)) else "0";
    x_fu_445_p3 <= 
        p_p2_i_i_reg_992 when (sel_tmp8_reg_998(0) = '1') else 
        p_assign_5_fu_439_p3;
end behav;
