# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/wnagds/Desktop/FPGA/22_ov5640_single/ov5640_single.srcs/sources_1/ip/my_rgb2gray_0/my_rgb2gray_0.xci
# IP: The module: 'my_rgb2gray_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wnagds/Desktop/FPGA/22_ov5640_single/ov5640_single.srcs/sources_1/ip/my_rgb2gray_0/constraints/my_rgb2gray_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_rgb2gray_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/wnagds/Desktop/FPGA/22_ov5640_single/ov5640_single.srcs/sources_1/ip/my_rgb2gray_0/my_rgb2gray_0.xci
# IP: The module: 'my_rgb2gray_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wnagds/Desktop/FPGA/22_ov5640_single/ov5640_single.srcs/sources_1/ip/my_rgb2gray_0/constraints/my_rgb2gray_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_rgb2gray_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
