// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMY_RGB2GRAY_H
#define XMY_RGB2GRAY_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmy_rgb2gray_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XMy_rgb2gray_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XMy_rgb2gray;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMy_rgb2gray_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMy_rgb2gray_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMy_rgb2gray_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMy_rgb2gray_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMy_rgb2gray_Initialize(XMy_rgb2gray *InstancePtr, u16 DeviceId);
XMy_rgb2gray_Config* XMy_rgb2gray_LookupConfig(u16 DeviceId);
int XMy_rgb2gray_CfgInitialize(XMy_rgb2gray *InstancePtr, XMy_rgb2gray_Config *ConfigPtr);
#else
int XMy_rgb2gray_Initialize(XMy_rgb2gray *InstancePtr, const char* InstanceName);
int XMy_rgb2gray_Release(XMy_rgb2gray *InstancePtr);
#endif

void XMy_rgb2gray_Start(XMy_rgb2gray *InstancePtr);
u32 XMy_rgb2gray_IsDone(XMy_rgb2gray *InstancePtr);
u32 XMy_rgb2gray_IsIdle(XMy_rgb2gray *InstancePtr);
u32 XMy_rgb2gray_IsReady(XMy_rgb2gray *InstancePtr);
void XMy_rgb2gray_EnableAutoRestart(XMy_rgb2gray *InstancePtr);
void XMy_rgb2gray_DisableAutoRestart(XMy_rgb2gray *InstancePtr);


void XMy_rgb2gray_InterruptGlobalEnable(XMy_rgb2gray *InstancePtr);
void XMy_rgb2gray_InterruptGlobalDisable(XMy_rgb2gray *InstancePtr);
void XMy_rgb2gray_InterruptEnable(XMy_rgb2gray *InstancePtr, u32 Mask);
void XMy_rgb2gray_InterruptDisable(XMy_rgb2gray *InstancePtr, u32 Mask);
void XMy_rgb2gray_InterruptClear(XMy_rgb2gray *InstancePtr, u32 Mask);
u32 XMy_rgb2gray_InterruptGetEnabled(XMy_rgb2gray *InstancePtr);
u32 XMy_rgb2gray_InterruptGetStatus(XMy_rgb2gray *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
